### ISSUE TITLE
Chat room got disconnected

### ISSUE THREAD

**Issue by hieunt1320** [RodrigoBertotti/flutter_chat_app_with_nodejs#7]
Dear Rodrigo,

i current stumble upon your project that is very similar to a project i wanted to created so i decided to use your code as a base to build mine and plan to expand on it to the future, though i got a few problem and i hope you can help me with it.

1. chat room got disconnected, iirc i saw this question being asked before but from my reading there hasnt been a answer to it yet ?, it i run one emulator phone and one physical phone, if i were to chat either consistently or just leave it there, the chat will be disconnected and i have to turn off nodejs and restart it to continue using it again

1.1 my problem also start from the one above too as i have my own project that also based on your code and i managed to send message between user just fine until either is due to disconnect or something im missing i got the error

vlance_sharpshooter

mobile_server\node_modules\typeorm\src\driver\mysql\MysqlQueryRunner.ts:222
                                new QueryFailedError(query, parameters, err),
                                ^
QueryFailedError: ER_TRUNCATED_WRONG_VALUE: Truncated incorrect DOUBLE value: '9970338569027054653L04117968'
    at Query.<anonymous> (mobile_server\node_modules\typeorm\src\driver\mysql\MysqlQueryRunner.ts:222:33)
    at Query.<anonymous> (mobile_server\node_modules\mysql\lib\Connection.js:526:10)
    at Query._callback (mobile_server\node_modules\mysql\lib\Connection.js:488:16)
    at Query.Sequence.end (mobile_server\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Query.ErrorPacket (mobile_server\node_modules\mysql\lib\protocol\sequences\Query.js:92:8)
    at Protocol._parsePacket (mobile_server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (mobile_server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (mobile_server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (mobile_server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (mobile_server\node_modules\mysql\lib\Connection.js:88:28) {
  query: 'UPDATE `message` SET `received_at` = ?, `sender_has_outdated_version` = ?, `updated_at` = CURRENT_TIMESTAMP WHERE `id` IN (?)',
  parameters: [ 2024-05-16T06:50:25.603Z, 1, '9970338569027054653L04117968' ],
  driverError: Error: ER_TRUNCATED_WRONG_VALUE: Truncated incorrect DOUBLE value: '9970338569027054653L04117968'
      at Query.Sequence._packetToError (mobile_server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)  
      at Query.ErrorPacket (mobile_server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
      at Protocol._parsePacket (mobile_server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
      at Parser._parsePacket (mobile_server\node_modules\mysql\lib\protocol\Parser.js:433:10)
      at Parser.write (mobile_server\node_modules\mysql\lib\protocol\Parser.js:43:10)
      at Protocol.write (mobile_server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
      at Socket.<anonymous> (mobile_server\node_modules\mysql\lib\Connection.js:88:28)
      at Socket.<anonymous> (mobile_server\node_modules\mysql\lib\Connection.js:526:10)
      at Socket.emit (node:events:519:28)
      at Socket.emit (node:domain:488:12)
      --------------------
      at Protocol._enqueue (mobile_server\node_modules\mysql\lib\protocol\Protocol.js:144:48)
      at PoolConnection.query (mobile_server\node_modules\mysql\lib\Connection.js:198:25)
      at mobile_server\node_modules\typeorm\src\driver\mysql\MysqlQueryRunner.ts:194:36
      at processTicksAndRejections (node:internal/process/task_queues:95:5) {
    code: 'ER_TRUNCATED_WRONG_VALUE',
    errno: 1292,
    sqlMessage: "Truncated incorrect DOUBLE value: '9970338569027054653L04117968'",
    sqlState: '22007',
    index: 0,
    sql: "UPDATE `message` SET `received_at` = '2024-05-16 13:50:25.603', `sender_has_outdated_version` = 1, `updated_at` = CURRENT_TIMESTAMP WHERE `id` IN ('9970338569027054653L04117968')"
  },
  code: 'ER_TRUNCATED_WRONG_VALUE',
  errno: 1292,
  sqlMessage: "Truncated incorrect DOUBLE value: '9970338569027054653L04117968'",
  sqlState: '22007',
  index: 0,
  sql: "UPDATE `message` SET `received_at` = '2024-05-16 13:50:25.603', `sender_has_outdated_version` = 1, `updated_at` = CURRENT_TIMESTAMP WHERE `id` IN ('9970338569027054653L04117968')"
}

this happen if i send a msg from user1 to user 2, user1 is fine, but if i logged into user2, there will be no more conversations, and it would stuck on loading,

i would love to be help with this and i will send more infomation if you needed, for example i created my own stream to list out the conversation now, maybe i missed something?, and if so why did it not work only after a bunch of message has been sent and it would seem only the receiver account got affected?

thank you in advance

**Comment by RodrigoBertotti** [comment]
Hello, looks like you are having problems with your custom code on top of my project, so it's better to investigate using other sources on the web

thank you for checking my project!
